name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Build with Maven
        run: |
          cd causalpath-cytoscape-app
          pwd
          mvn compile
          mvn clean install
      - name: Get Version 
        id: get_version 
        run: |
          cp /home/runner/work/causalpath_cytoscape_app/causalpath_cytoscape_app/causalpath-cytoscape-app/target/*.jar causalpath-cytoscape-app-latest.jar 
      - name: Release
        uses: softprops/action-gh-release@v1
        with: 
          name: 'latest'
          tag_name: 'latest'
          prerelease: true
          files: /home/runner/work/causalpath_cytoscape_app/causalpath_cytoscape_app/causalpath-cytoscape-app/target/causalpath-cytoscape-app-latest.jar
